SUBJECT: mailto:help@example.com
VAPID_PUBLIC_KEY: <BDua2QW982Mf5_xO85P6HPHeixhkuDqe3tsJz8ajIinJjzb5SViVjf5cIimn-mCTMFkKImi0dLlheUM-mzOOWwE=>
VAPID_PRIVATE_KEY: <OI_eN3rXXoBkfF397VPnGpjpZDT8GM01x5p9TKo7t_c=>